apiVersion: apps/v1
kind: Deployment
metadata:
   name: guruweb
spec:
   replicas: 2
   selector:
      matchLabels:
         app: guruweb
   template:
      metadata:
         labels:
            app: guruweb
      spec:
         containers:
            - name: guruweb
              image: ardl-dockerhub01:5000/level3/crm.guru:2.29.0.0
              imagePullPolicy: Always
